# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cname', models.CharField(max_length=50)),
                ('c_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.IntegerField()),
                ('test1_max_marks', models.IntegerField(default=100)),
                ('test2', models.IntegerField()),
                ('test2_max_marks', models.IntegerField(default=100)),
                ('assn', models.IntegerField()),
                ('assn_max_marks', models.IntegerField(default=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('suser_name', models.CharField(max_length=25)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('csem', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sem_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('tuser_name', models.CharField(max_length=25)),
                ('tname', models.CharField(max_length=50)),
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuser_name', models.CharField(max_length=25)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
        migrations.AddField(
            model_name='marks',
            name='suser_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
