# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20171029_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='assn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='test1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='test2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
