# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_teacher_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_key',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
